---
title: "Week 1 Notebook"
output: html_notebook
---

```{r}
# installed.packages()
library(ggplot2)
library(gamlss)
## Loading required package: splines
## Loading required package: gamlss.data
##
## Attaching package: ’gamlss.data’
## The following object is masked from ’package:datasets’:
##
##     sleep
## Loading required package: gamlss.dist
## Loading required package: MASS
## Loading required package: nlme
## Loading required package: parallel
##  **********   GAMLSS Version 5.4-12  **********
## For more on GAMLSS look at https://www.gamlss.com/
## Type gamlssNews() to see new features/changes/bug fixes.
library(nnet)
search()
```
```{r}
rm(list=ls()) 
ls()
```

```{r}
# for functions you know the name
?plot
## Help on topic 'plot' was found in the following packages:
##
##
##
##
##
##
## Using the first match ...
```

```{r}
??"neural network"
```
```{r}
help(package="nnet")
help(package="ggplot2")
####################################################################
```

Vectors

```{r}
x <- 1:100
#----------------------------- 
# which class it belongs to? 
class(x)
print(x)
head(x)
tail(x, 10)
x[3:6]
```

```{r}
# create a numeric vector
# rnorm() is a function generating normally distributed variables
# witn 0 mean 1 sd
x1 <- rnorm(1000) 
class(x1)
plot(x1)
hist(x1)
library(MASS)
truehist(x1)
lines(density(x1)) 
x1[10:20]
#overwriting an element of x
x1[1] <- 2
x1[1]
```

# 3 Factors

```{r}
f <- gl(2,500)
head(f) ; tail(f)
class(f)
```

```{r}
# this is numeric not a factor
ff <- c(rep(1,500), rep(2,500)) 
class(ff) # not a factor
# declare it as a factor
fff <- factor(ff) 
levels(fff)
class(fff)
```
```{r}
plot(ff); title("numeric") # as factor
plot(fff); title("factor") 
plot(x1~ff)
plot(x1~fff)
```
```{r}
#---------------------------------------------- # character vectors
C <- c("you", "me")
C
levels(fff) <- C
levels(fff)
head(fff)
```

```{r}
match("me", C)
# for more character functions see
?grep
```


# 4 List
```{r}
# lists
L <- list(y=c(1,2,3), x=2, z=rep(3,5), c=c("hi") ) 
L
# get
L[[1]]
L[["y"]]
L$y

L[1] # is different from
L[[1]]
```

# 5 Matrices

```{r}
######################################################################## # matrices
M <- matrix(0, ncol=3, nrow=5)
M

#--------------------------------------------
A <- matrix(1:15, ncol=3, nrow=5)
A

#--------------------------------------------
# get a column of the matrix A
A[,1]

A[1,]

#--------------------------------------------
# get an element
A[1,2]

#--------------------------------------------
# get a subset
A[1:2, 2:3]

#--------------------------------------------
```

```{r}
# transpose
t(A)

#--------------------------------------------
# multiply by a scalar
2*A

#-------------------------------------------- # multiply by a vector
# (5x3) (3,1) result (5x1)
# Ac=v
A%*%c(1,2,3)

#-------------------------------------------- # multiply by a matrix
B <- matrix(rnorm(9), ncol=3)
B
A%*%B

#---------------------------------------------
B <- matrix(rnorm(9), ncol=3)
# inverse of a matrix
C<- solve(B)
C%*%B # equal the identity matrix

matplot(A) 
matplot(A, type="l")
```
# 6 Fitting a linear model

```{r}
library(gamlss) 
data(abdom) 
head(abdom)
plot(y~x, data=abdom) 
# or
plot(abdom$x, abdom$y)

```

Fit a linear model to the data
```{r}
m1 <- lm(y~x, data=abdom) 
summary(m1)

# the coefficients
coef(m1)

# the fitted values
head(fitted(m1))

# add the the fitted values ion the plot
#
plot(y~x, data=abdom)
lines(fitted(m1)~abdom$x, col="red", lwd=3)
```

# 7 Creating a function

```{r}
my.mean <- function(x) {
  mean <- sum(x)/length(x)
  mean 
}
my.mean(x1)

my.mean(f)

my.mean1 <- function(x) {
  if (!is.numeric(x)) stop("the argument is not numeric") 
  mean <- sum(x)/length(x)
  mean
} 

my.mean1(x1)

my.mean1(f)
```
```{r}
library(gamlss)
library(gamlss.data)
library(ggplot2)
library(dplyr)

data(dbbmi)
plot(bmi~age, data=dbbmi)
hist(dbbmi$age)
p <- ggplot(dbbmi, aes(x = bmi)) + 
  geom_histogram(binwidth = 1, fill = "blue", color = "black") + 
  facet_wrap(~ age, scales = "free_y") + 
  theme_minimal() +
  labs(title = "BMI Distribution by Age", x = "BMI", y = "Frequency")

# Display the plot
print(p)
```

